name: build
on: push
jobs:
  build-web:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.9'
          channel: stable
      - name: Analyze & Test
        run: |
          flutter pub get
          flutter format --set-exit-if-changed .
          flutter analyze
      - name: Build
        run: |
          flutter build windows
